name: drupal9-lando-composer-starter
recipe: drupal9
config:
  webroot: web
  php: '8.0'
  via: apache:2.4
  database: mariadb
  xdebug: true
proxy:
  appserver:
    - drupal9.lndo.site
services:
  appserver:
    xdebug: debug
    config:
      conf: conf/php/php.ini
    build_as_root:
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload
  database:
    config:
      database: conf/mysql/my.cnf
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
    app_mount: false
    hosts:
      - database
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    user: root
events:
  pre-start:
    - appserver: composer install --ignore-platform-reqs
